/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.corporate.knowledge.test.model.impl;

import com.corporate.knowledge.test.model.Producto;
import com.corporate.knowledge.test.model.ProductoModel;
import com.corporate.knowledge.test.model.ProductoSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the Producto service. Represents a row in the &quot;knowledgeTest_Producto&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>ProductoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProductoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductoImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class ProductoModelImpl
	extends BaseModelImpl<Producto> implements ProductoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a producto model instance should use the <code>Producto</code> interface instead.
	 */
	public static final String TABLE_NAME = "knowledgeTest_Producto";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"productId", Types.BIGINT},
		{"name", Types.VARCHAR}, {"creationDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("productId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("creationDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table knowledgeTest_Producto (uuid_ VARCHAR(75) null,productId LONG not null primary key,name VARCHAR(75) null,creationDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table knowledgeTest_Producto";

	public static final String ORDER_BY_JPQL =
		" ORDER BY producto.productId DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY knowledgeTest_Producto.productId DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long UUID_COLUMN_BITMASK = 1L;

	public static final long PRODUCTID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Producto toModel(ProductoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Producto model = new ProductoImpl();

		model.setUuid(soapModel.getUuid());
		model.setProductId(soapModel.getProductId());
		model.setName(soapModel.getName());
		model.setCreationDate(soapModel.getCreationDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Producto> toModels(ProductoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Producto> models = new ArrayList<Producto>(soapModels.length);

		for (ProductoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ProductoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _productId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProductId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _productId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Producto.class;
	}

	@Override
	public String getModelClassName() {
		return Producto.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Producto, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Producto, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Producto, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Producto)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Producto, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Producto, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Producto)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Producto, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Producto, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Producto>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Producto.class.getClassLoader(), Producto.class,
			ModelWrapper.class);

		try {
			Constructor<Producto> constructor =
				(Constructor<Producto>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Producto, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Producto, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Producto, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Producto, Object>>();
		Map<String, BiConsumer<Producto, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Producto, ?>>();

		attributeGetterFunctions.put("uuid", Producto::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Producto, String>)Producto::setUuid);
		attributeGetterFunctions.put("productId", Producto::getProductId);
		attributeSetterBiConsumers.put(
			"productId", (BiConsumer<Producto, Long>)Producto::setProductId);
		attributeGetterFunctions.put("name", Producto::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Producto, String>)Producto::setName);
		attributeGetterFunctions.put("creationDate", Producto::getCreationDate);
		attributeSetterBiConsumers.put(
			"creationDate",
			(BiConsumer<Producto, Date>)Producto::setCreationDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getProductId() {
		return _productId;
	}

	@Override
	public void setProductId(long productId) {
		_columnBitmask = -1L;

		_productId = productId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public Date getCreationDate() {
		return _creationDate;
	}

	@Override
	public void setCreationDate(Date creationDate) {
		_creationDate = creationDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Producto.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Producto toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Producto>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProductoImpl productoImpl = new ProductoImpl();

		productoImpl.setUuid(getUuid());
		productoImpl.setProductId(getProductId());
		productoImpl.setName(getName());
		productoImpl.setCreationDate(getCreationDate());

		productoImpl.resetOriginalValues();

		return productoImpl;
	}

	@Override
	public int compareTo(Producto producto) {
		int value = 0;

		if (getProductId() < producto.getProductId()) {
			value = -1;
		}
		else if (getProductId() > producto.getProductId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Producto)) {
			return false;
		}

		Producto producto = (Producto)obj;

		long primaryKey = producto.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		ProductoModelImpl productoModelImpl = this;

		productoModelImpl._originalUuid = productoModelImpl._uuid;

		productoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Producto> toCacheModel() {
		ProductoCacheModel productoCacheModel = new ProductoCacheModel();

		productoCacheModel.uuid = getUuid();

		String uuid = productoCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			productoCacheModel.uuid = null;
		}

		productoCacheModel.productId = getProductId();

		productoCacheModel.name = getName();

		String name = productoCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			productoCacheModel.name = null;
		}

		Date creationDate = getCreationDate();

		if (creationDate != null) {
			productoCacheModel.creationDate = creationDate.getTime();
		}
		else {
			productoCacheModel.creationDate = Long.MIN_VALUE;
		}

		return productoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Producto, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Producto, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Producto, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Producto)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Producto, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Producto, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Producto, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Producto)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Producto>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _productId;
	private String _name;
	private Date _creationDate;
	private long _columnBitmask;
	private Producto _escapedModel;

}