/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.corporate.knowledge.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Candidate service. Represents a row in the &quot;knowledgeTest_Candidate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.corporate.knowledge.test.model.impl.CandidateModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.corporate.knowledge.test.model.impl.CandidateImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Candidate
 * @generated
 */
@ProviderType
public interface CandidateModel extends BaseModel<Candidate> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a candidate model instance should use the {@link Candidate} interface instead.
	 */

	/**
	 * Returns the primary key of this candidate.
	 *
	 * @return the primary key of this candidate
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this candidate.
	 *
	 * @param primaryKey the primary key of this candidate
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this candidate.
	 *
	 * @return the uuid of this candidate
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this candidate.
	 *
	 * @param uuid the uuid of this candidate
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the candidate ID of this candidate.
	 *
	 * @return the candidate ID of this candidate
	 */
	public long getCandidateId();

	/**
	 * Sets the candidate ID of this candidate.
	 *
	 * @param candidateId the candidate ID of this candidate
	 */
	public void setCandidateId(long candidateId);

	/**
	 * Returns the name of this candidate.
	 *
	 * @return the name of this candidate
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this candidate.
	 *
	 * @param name the name of this candidate
	 */
	public void setName(String name);

	/**
	 * Returns the company of this candidate.
	 *
	 * @return the company of this candidate
	 */
	@AutoEscape
	public String getCompany();

	/**
	 * Sets the company of this candidate.
	 *
	 * @param company the company of this candidate
	 */
	public void setCompany(String company);

	/**
	 * Returns the passed of this candidate.
	 *
	 * @return the passed of this candidate
	 */
	public boolean getPassed();

	/**
	 * Returns <code>true</code> if this candidate is passed.
	 *
	 * @return <code>true</code> if this candidate is passed; <code>false</code> otherwise
	 */
	public boolean isPassed();

	/**
	 * Sets whether this candidate is passed.
	 *
	 * @param passed the passed of this candidate
	 */
	public void setPassed(boolean passed);

	/**
	 * Returns the points of this candidate.
	 *
	 * @return the points of this candidate
	 */
	public int getPoints();

	/**
	 * Sets the points of this candidate.
	 *
	 * @param points the points of this candidate
	 */
	public void setPoints(int points);

	/**
	 * Returns the test date of this candidate.
	 *
	 * @return the test date of this candidate
	 */
	public Date getTestDate();

	/**
	 * Sets the test date of this candidate.
	 *
	 * @param testDate the test date of this candidate
	 */
	public void setTestDate(Date testDate);

	/**
	 * Returns the location of this candidate.
	 *
	 * @return the location of this candidate
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this candidate.
	 *
	 * @param location the location of this candidate
	 */
	public void setLocation(String location);

}